import { Router } from 'express';

const jobRouter = Router();

const jobs = [
    {
        id: 1,
        title: 'Software Engineer',
        company: 'Google',
        location: 'Mountain View, CA',
        level: 'L4',
        industry: 'Tech',
        experience: '2-4 years',
        baseSalary: '150,000',
        total: '225,000',
        workingHours: 45,
        stockOptions: true,
        bonuses: 20000,
        welfare: ['Free meals', 'On-site gym', 'Game room'],
        skills: ['JavaScript', 'React', 'GCP'],
        companySize: 'Enterprise',
        employmentType: 'Full-time',
        remote: false,
        education: "Master's",
        bootcampGraduate: false,
        previousRole: 'Junior Developer',
        previousSalary: '100,000',
        promotionFrequency: 'Every 2 years',
        workLifeBalance: 4.2,
        jobSatisfaction: 4.5,
        gender: 'Male',
        ageRange: '25-30'
    },
    {
        id: 2,
        title: 'Software Engineer',
        company: 'Microsoft',
        location: 'Redmond, WA',
        level: 'SDE II',
        industry: 'Tech',
        experience: '3-5 years',
        baseSalary: '140,000',
        total: '200,000',
        workingHours: 42,
        stockOptions: true,
        bonuses: 15000,
        welfare: ['Flexible hours', 'Remote work options'],
        skills: ['C#', 'Azure', '.NET'],
        companySize: 'Enterprise',
        employmentType: 'Full-time',
        remote: true,
        education: "Bachelor's",
        bootcampGraduate: false,
        previousRole: 'Software Intern',
        previousSalary: '90,000',
        promotionFrequency: 'Every 3 years',
        workLifeBalance: 4.0,
        jobSatisfaction: 4.2,
        gender: 'Female',
        ageRange: '30-35'
    },
    {
        id: 3,
        title: 'Backend Engineer',
        company: 'Amazon',
        location: 'Seattle, WA',
        level: 'L5',
        industry: 'E-commerce',
        experience: '2-3 years',
        baseSalary: '130,000',
        total: '210,000',
        workingHours: 50,
        stockOptions: true,
        bonuses: 18000,
        welfare: ['Health insurance', 'Amazon Prime membership'],
        skills: ['Java', 'AWS', 'Spring Boot'],
        companySize: 'Enterprise',
        employmentType: 'Full-time',
        remote: false,
        education: 'PhD',
        bootcampGraduate: false,
        previousRole: 'Research Engineer',
        previousSalary: '110,000',
        promotionFrequency: 'Every 4 years',
        workLifeBalance: 3.5,
        jobSatisfaction: 4.0,
        gender: 'Male',
        ageRange: '35-40'
    },
    {
        id: 4,
        title: 'Frontend Developer',
        company: 'Facebook',
        location: 'Menlo Park, CA',
        level: 'E4',
        industry: 'Social Media',
        experience: '4-6 years',
        baseSalary: '160,000',
        total: '240,000',
        workingHours: 40,
        stockOptions: true,
        bonuses: 25000,
        welfare: ['Free meals', 'Wellness stipend', 'Mental health support'],
        skills: ['React', 'TypeScript', 'GraphQL'],
        companySize: 'Enterprise',
        employmentType: 'Full-time',
        remote: false,
        education: "Bachelor's",
        bootcampGraduate: false,
        previousRole: 'UI Developer',
        previousSalary: '120,000',
        promotionFrequency: 'Every 2.5 years',
        workLifeBalance: 4.5,
        jobSatisfaction: 4.8,
        gender: 'Female',
        ageRange: '28-33'
    },
    {
        id: 5,
        title: 'Data Scientist',
        company: 'Apple',
        location: 'Cupertino, CA',
        level: 'IC3',
        industry: 'Consumer Electronics',
        experience: '3-5 years',
        baseSalary: '155,000',
        total: '230,000',
        workingHours: 38,
        stockOptions: true,
        bonuses: 22000,
        welfare: ['Discounts on Apple products', 'Gym membership'],
        skills: ['Python', 'TensorFlow', 'SQL'],
        companySize: 'Enterprise',
        employmentType: 'Full-time',
        remote: false,
        education: "Master's",
        bootcampGraduate: false,
        previousRole: 'Data Analyst',
        previousSalary: '100,000',
        promotionFrequency: 'Every 3 years',
        workLifeBalance: 4.3,
        jobSatisfaction: 4.6,
        gender: 'Male',
        ageRange: '30-35'
    },
    {
        id: 6,
        title: 'Full-Stack Developer',
        company: 'Netflix',
        location: 'Los Gatos, CA',
        level: 'E5',
        industry: 'Entertainment',
        experience: '2-4 years',
        baseSalary: '145,000',
        total: '220,000',
        workingHours: 42,
        stockOptions: true,
        bonuses: 20000,
        welfare: ['Flexible work schedule', 'Streaming perks'],
        skills: ['React', 'Node.js', 'GraphQL'],
        companySize: 'Enterprise',
        employmentType: 'Full-time',
        remote: true,
        education: 'Bootcamp',
        bootcampGraduate: true,
        previousRole: 'Self-Taught Developer',
        previousSalary: '80,000',
        promotionFrequency: 'Every 2 years',
        workLifeBalance: 4.0,
        jobSatisfaction: 4.3,
        gender: 'Female',
        ageRange: '25-30'
    },
    {
        id: 7,
        title: 'DevOps Engineer',
        company: 'Uber',
        location: 'San Francisco, CA',
        level: 'L4',
        industry: 'Transportation',
        experience: '3-5 years',
        baseSalary: '135,000',
        total: '205,000',
        workingHours: 45,
        stockOptions: true,
        bonuses: 18000,
        welfare: ['Free Uber rides', 'Tech stipend'],
        skills: ['AWS', 'Kubernetes', 'Terraform'],
        companySize: 'Enterprise',
        employmentType: 'Full-time',
        remote: false,
        education: "Bachelor's",
        bootcampGraduate: false,
        previousRole: 'SysAdmin',
        previousSalary: '95,000',
        promotionFrequency: 'Every 3 years',
        workLifeBalance: 3.9,
        jobSatisfaction: 4.0,
        gender: 'Male',
        ageRange: '28-34'
    },
    {
        id: 8,
        title: 'Machine Learning Engineer',
        company: 'Airbnb',
        location: 'San Francisco, CA',
        level: 'L5',
        industry: 'Hospitality',
        experience: '2-4 years',
        baseSalary: '140,000',
        total: '215,000',
        workingHours: 40,
        stockOptions: true,
        bonuses: 22000,
        welfare: ['Travel credits', 'Wellness stipend'],
        skills: ['Python', 'TensorFlow', 'Scikit-learn'],
        companySize: 'Enterprise',
        employmentType: 'Full-time',
        remote: true,
        education: "Master's",
        bootcampGraduate: false,
        previousRole: 'Data Scientist',
        previousSalary: '110,000',
        promotionFrequency: 'Every 2.5 years',
        workLifeBalance: 4.4,
        jobSatisfaction: 4.6,
        gender: 'Female',
        ageRange: '26-32'
    },
    {
        id: 9,
        title: 'Cybersecurity Engineer',
        company: 'Salesforce',
        location: 'San Francisco, CA',
        level: 'E5',
        industry: 'SaaS',
        experience: '3-5 years',
        baseSalary: '150,000',
        total: '225,000',
        workingHours: 42,
        stockOptions: true,
        bonuses: 20000,
        welfare: ['On-site daycare', 'Tech stipend'],
        skills: ['Python', 'Penetration Testing', 'Cloud Security'],
        companySize: 'Enterprise',
        employmentType: 'Full-time',
        remote: false,
        education: "Bachelor's",
        bootcampGraduate: false,
        previousRole: 'Security Analyst',
        previousSalary: '105,000',
        promotionFrequency: 'Every 3 years',
        workLifeBalance: 3.8,
        jobSatisfaction: 4.1,
        gender: 'Male',
        ageRange: '30-36'
    },
    {
        id: 10,
        title: 'Product Manager',
        company: 'Oracle',
        location: 'Redwood City, CA',
        level: 'PM2',
        industry: 'Cloud Computing',
        experience: '5-7 years',
        baseSalary: '160,000',
        total: '240,000',
        workingHours: 45,
        stockOptions: true,
        bonuses: 25000,
        welfare: ['Conference budget', 'Education reimbursement'],
        skills: ['Agile', 'SQL', 'Market Analysis'],
        companySize: 'Enterprise',
        employmentType: 'Full-time',
        remote: false,
        education: 'MBA',
        bootcampGraduate: false,
        previousRole: 'Business Analyst',
        previousSalary: '130,000',
        promotionFrequency: 'Every 3.5 years',
        workLifeBalance: 4.1,
        jobSatisfaction: 4.4,
        gender: 'Female',
        ageRange: '32-38'
    },
    {
        id: 11,
        title: 'Game Developer',
        company: 'Riot Games',
        location: 'Los Angeles, CA',
        level: 'Mid-Level',
        industry: 'Gaming',
        experience: '2-4 years',
        baseSalary: '120,000',
        total: '185,000',
        workingHours: 50,
        stockOptions: false,
        bonuses: 15000,
        welfare: ['Free game access', 'Team outings'],
        skills: ['C++', 'Unity', 'Game Physics'],
        companySize: 'Enterprise',
        employmentType: 'Full-time',
        remote: false,
        education: "Bachelor's",
        bootcampGraduate: false,
        previousRole: 'Junior Developer',
        previousSalary: '90,000',
        promotionFrequency: 'Every 3 years',
        workLifeBalance: 3.5,
        jobSatisfaction: 4.2,
        gender: 'Male',
        ageRange: '24-30'
    }
];

jobRouter.get('/', (req, res) => {
    const { title } = req.query;
    console.log('title:', title);

    let filteredJobs = jobs;

    if (title) {
        filteredJobs = jobs.filter((job) => job.title.toLowerCase().includes(title.toLowerCase()));
    }

    res.json(filteredJobs);
});

export { jobRouter };
